# Generated by Django 5.2 on 2025-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (Recommended)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o', help_text='The OpenAI model used by the assistant for this project.', max_length=50),
        ),
    ]
