# Generated by Django 5.2 on 2025-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (Recommended)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.5-preview', 'GPT-4.5 Preview')], default='gpt-4o', help_text='The OpenAI model used by the assistant for this project.', max_length=50),
        ),
    ]
