# Generated by Django 5.2 on 2025-05-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o (Recommended)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.5-preview', 'GPT-4.5 Preview')], default='gpt-4o', help_text='The OpenAI model used for this chat session.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant with access to web search and other tools. Use tools when appropriate to provide accurate and up-to-date information.', help_text='System instructions for the AI assistant')),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=10),
        ),
        migrations.CreateModel(
            name='IndependentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.independentchatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
